--- #YAML:1.0
name:               Audio-Ecasound
version:            1.01
abstract:           Perl binding to the ecasound sampler, recorder, fx-processor
author:
    - Brad Bowman <eci-perl@bereft.net>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
